---
- hosts: all
  sudo: yes
  vars:
    http_port: 80
    doc_dir: /ansible/
    doc_root: /var/www/html/ansible/
    max_clients: 5

  vars_prompt:
    - name: username
      prompt:  What is your name?  What is your Quest?  What is your fav color?

  tasks:
  - name: Ensure that Apache is installed
    yum: name=httpd state=present
    when: ansible_os_family == "Cent Os"

  - name: Start Apache Services
    service: name=httpd enabled=yes state=started
  - name: copying the httpd file
    template: src=/etc/httpd/conf/httpd.conf  dest=/templates/httpd.j2 
  - name: Deploy configuration File
    template: src=/templates/httpd.j2 dest=/etc/httpd/conf/httpd.conf
    notify:
      - Restart Apache

  - name: Copy Site Files
    template: src=templates/index.j2 dest={{ doc_root }}/index.html

  handlers:
     - name: Restart Apache
       service: name=httpd state=restarted
